In [4]:
import pandas as pd
from scipy.stats import kurtosis, skew
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
bajar_monte = pd.read_csv("./Data/bajar_monte.csv")
subir_monte = pd.read_csv("./Data/subir_monte.csv")
bici = pd.read_csv("./Data/bici.csv")
coche = pd.read_csv("./Data/coche.csv")

df_list = [bajar_monte, subir_monte, bici, coche]

In [7]:
df = pd.DataFrame()
df_bici = df.append(bici.describe())
df_coche = df.append(coche.describe())
df_bajar_monte = df.append(bajar_monte.describe())
df_subir_monte = df.append(subir_monte.describe())

In [8]:
df_coche

,Time (s),Linear Acceleration x (m/s^2),Linear Acceleration y (m/s^2),Linear Acceleration z (m/s^2),Absolute acceleration (m/s^2)
count,63805.000000,63805.000000,63805.000000,63805.000000,63805.000000
mean,320.446877,0.030946,-0.094559,-0.012847,1.083306
std,185.023165,0.792746,0.615801,1.024482,0.945366
min,0.012126,-10.186724,-10.297078,-28.683315,0.014331
25%,160.214890,-0.240204,-0.433716,-0.433510,0.553190
50%,320.429886,0.054942,-0.096068,-0.010302,0.874589
75%,480.669546,0.382061,0.232150,0.417792,1.344400
max,640.947658,10.071413,7.792626,33.958124,35.222364